x="Leading university"
print("STRING:")
print("\t"+x)
print("UPPER CASE STRING: ")
print("\t"+x.upper())
print("LOWER CASE STRING: ")
print("\t"+x.lower())
print("LENGTH OF STRING: ")
print("\t",len(x))
print("SPLITE STRING: ")
print("\t",x.split("i"))
print("STRIP STRING: ")
print("\t",x.strip())
print("REPLACE STRING: ")
print("\t",x.replace("i","I"))
print("3RD ELEMENT OF STRING: ")
print("\t",x[2])
print("6TH ELEMENT OF STRING: ")
print("\t",x[5])
print("2ND-7TH ELEMENT OF STRING: ")
print("\t",x[1:7])
print("3RD-LAST ELEMENT OF STRING: ")
print("\t",x[2:])
print("1ST-9TH ELEMENT OF STRING: ")
print("\t",x[:9])
print("REVERSE INDEZXING OF STRING: ")
print("\t",x[-8:-6])